### ISSUE TITLE
Is osx-arm64 version possible?

### ISSUE THREAD

**Issue by psobolewskiPhD** [conda-forge/stardist-feedstock#3]
### Comment:
```
Executing the query stardist

conda-forge/osx-arm64                              @ 523.2kB/s  4.2s
conda-forge/noarch                                 @   1.7MB/s  4.8s


No entries matching "stardist" found
```
Is it possible to make an osx-arm64 version?
Ideally one that works with/respects the Apple tensorflow env?
https://developer.apple.com/metal/tensorflow-plugin/

**Comment by uschmidt83** [comment]
I don't know how this works on conda-forge, but we will make arm64 wheels available on PyPI in the next release.

Building the wheels already works, only [tests](https://github.com/stardist/stardist/actions/runs/2104862588) on macOS with Python 3.6 fail, but we just might drop support for 3.6.

**Comment by psobolewskiPhD** [comment]
Awesome! great to hear!
I think there is a arm64 migration thingie on conda-forge, but I'm not smart enough to grasp it—it's all very complex. Ideally both conda and pip JustWork.

**Comment by psobolewskiPhD** [comment]
I took a look at the docs here:
https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock
Looks like y'all need to make a PR to add `stardist` to :
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt

**Comment by uschmidt83** [comment]
I opened a PR https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2861 but am not sure what to do next. It also seems that all "parents" of StarDist need to be on osx-arm64 first.

**Comment by psobolewskiPhD** [comment]
As far as I can tell only `csbdeep` is missing an arm64 build on conda-forge and it's depends seem to already be arm64.
So I guess the same PR to conda-forge-pinning-feedstock needs to be made for `csbdeep`

**Comment by uschmidt83** [comment]
I don't really know, but I've also open a PR for csbdeep: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2862

I thought this wouldn't be necessary since csbdeep is platform-agnostic package.

**Comment by psobolewskiPhD** [comment]
> I thought this wouldn't be necessary since csbdeep is platform-agnostic package.

I dunno. Here's what I get on my M1:
```
>mamba repoquery search csbdeep         
Executing the query csbdeep

conda-forge/osx-arm64                              @   2.1MB/s  1.2s
conda-forge/noarch                                 @   3.2MB/s  2.7s


No entries matching "csbdeep" found
```

**Comment by uschmidt83** [comment]
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2862#issuecomment-1124742179

**Comment by psobolewskiPhD** [comment]
@goanpeca Any idea why the arm64 migrator hasn't been triggered for `stardist` or `csbdeep`?

**Comment by goanpeca** [comment]
Stardist is there, so I guess it is just a matter of time 

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt#L857

?

**Comment by psobolewskiPhD** [comment]
Ah, patience then I guess.
I was confused because `fastremap` is Line 875 and the migration bot triggered like same day and it's already live.

**Comment by goanpeca** [comment]
Yeah, I am not sure how the bot is prioritizing, maybe fastremap did not need additional dependencies. I am just guessing here :-p

**Comment by psobolewskiPhD** [comment]
Is it possible the issue is here:
https://conda-forge.org/status/#current_migrations
<img width="913" alt="image" src="https://user-images.githubusercontent.com/76622105/170817238-c6391a3a-e149-45f9-952b-7e826ea8b86b.png">

Tensorflow was manually migrated and has arm64 builds:
```
Executing the query tensorflow

conda-forge/osx-arm64                                2.5MB @   1.6MB/s  1.7s
conda-forge/noarch                                 @   3.4MB/s  2.6s


 Name       Version Build               Channel              
──────────────────────────────────────────────────────────────
 tensorflow 2.8.1   cpu_py310h6ecea76_0 conda-forge/osx-arm64
 tensorflow 2.8.1   cpu_py38h4487131_0  conda-forge/osx-arm64
 tensorflow 2.8.1   cpu_py39h2839aeb_0  conda-forge/osx-arm64
 tensorflow 2.8.0   cpu_py310h6ecea76_0 conda-forge/osx-arm64
 tensorflow 2.8.0   cpu_py38h4487131_0  conda-forge/osx-arm64
 tensorflow 2.8.0   cpu_py39h2839aeb_0  conda-forge/osx-arm64
```

I checked that other `child` package `sleepecg`. It seemed to experience the same issue and ended up manually migrated, and is now live.

**Comment by psobolewskiPhD** [comment]
> I don't really know, but I've also open a PR for csbdeep: [conda-forge/conda-forge-pinning-feedstock#2862](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2862)
> 
> I thought this wouldn't be necessary since csbdeep is platform-agnostic package.

So should `csbdeep` be under `/noarch`?
Currently when using a rosetta env I do see csbdeep:
```
conda-forge/noarch                                 @   2.8MB/s  3.2s
conda-forge/osx-64                                 @   2.8MB/s  8.1s


 Name    Version Build           Channel           
────────────────────────────────────────────────────
 csbdeep 0.7.1   py310h2ec42d9_0 conda-forge/osx-64
 csbdeep 0.7.1   py37hf985489_0  conda-forge/osx-64
 csbdeep 0.7.1   py38h50d1736_0  conda-forge/osx-64
 csbdeep 0.7.1   py39h6e9494a_0  conda-forge/osx-64
 csbdeep 0.7.0   py310h2ec42d9_0 conda-forge/osx-64
 csbdeep 0.7.0   py37hf985489_0  conda-forge/osx-64
 csbdeep 0.7.0   py38h50d1736_0  conda-forge/osx-64
 csbdeep 0.7.0   py39h6e9494a_0  conda-forge/osx-64
```
But on pypi the wheels are `-any-`

Edit:
I gave this a whirl on `csbdeep-feedstock`. It requires changing TF requirements to >2.4, so I'm not sure it's the way to go:
https://github.com/conda-forge/csbdeep-feedstock/pull/7

**Comment by uschmidt83** [comment]
Cf #7 

I approved the respective PR for csbdeep earlier today

**Comment by uschmidt83** [comment]
I just merged https://github.com/conda-forge/stardist-feedstock/pull/7.

@psobolewskiPhD, would you be so kind and please test the osx-arm64 version once it's up on conda-forge?

**Comment by psobolewskiPhD** [comment]
It's live!
`mamba create --name test-env2 python=3.9 stardist`
works.
Running the example code from `stardist/stardist` works just fine.
~130 ms per step after warmup.

**Comment by psobolewskiPhD** [comment]
This versus ~40 ms per step after `pip install tensorflow-metal` in the same env.
To be expected, I guess. So the docs need to be clear that conda-forge solution on macOS at least is CPU only and for GPU you need to also do `pip install tensorflow-metal`.

**Comment by psobolewskiPhD** [comment]
I did `mamba create --name test-env2 python=3.9 stardist-napari` too. Everything installs, but it installs napari with pyside backend which gives errors when opening an image, so different issue—I'll make on on napari repo.

**Comment by psobolewskiPhD** [comment]
If I:
`mamba create --name test-env2 python=3.9 pyqt`
or `mamba create --name test-env2 python=3.9 napari`
then `mamba install stardist-napari` is fine (slow, as noted above).

So yeah, not sure why `mamba create --name test-env2 python=3.9 stardist-napari` installs the pyside2 backend and why that one doesn't work, but both stardist and stardist-napari packages seem fine.
Edit: definitely a vispy/pyside2 issue not related to this.
@jaimergp is there anyway to get conda to install `tensorflow-metal` off pypi? I think not, right? So just need to document it?

**Comment by uschmidt83** [comment]
@psobolewskiPhD thank you very much for testing!

At the moment, the StarDist documentation doesn't even mention that installation via conda-forge is also possible. I guess we should do that and then also mention the subtleties regarding osx-arm64...

**Comment by jaimergp** [comment]
> @jaimergp is there anyway to get conda to install tensorflow-metal off pypi? I think not, right? So just need to document it?

Unfortunately not, at least for now. [There has been some discussion here](https://github.com/conda-forge/conda-forge.github.io/issues/1537) if you are curious.

**Comment by psobolewskiPhD** [comment]
I think this can be closed. The install of stardist via conda-forge works fine on arm64 macOS. Perhaps there can be a runtime check for tensorflow-metal and a warning to the user to install it for GPU support? but that's a different issue.
